name: Vishnu
affiliation: asdf
style: double

reconfig: false

# Please do not change manually
cache_dir: /home/vishnu/reportinator-test/cache
install_dir: /home/vishnu/reportinator-test/share
source_dir: /home/vishnu/reportinator-test
installed: false
