name: Vishnu
affiliation: NISER
style: double

reconfig: False

# Please do not change manually
cache_dir: /home/vishnu/newrep/cache
install_dir: /home/vishnu/newrep/share
source_dir: /home/vishnu/newrep
installed: False
